### ISSUE TITLE
Position and reference base problem

### ISSUE THREAD

**Issue by yuxinPenny** [sihaohuanguc/Nanopore_psU#1]
Dear author,

  I used your package to find psU site from sample. Regarding the results, 

transcript_ID,position,base_type,coverage,prob_unmodified,prob_modified
chr1_R,1026162,T,21,0.96,0.04
chr1_R,1026166,T,21,0.98,0.02
chr1_R,1026168,T,21,1.0,0.0

what does R mean, does it mean plus strand or minus strand?

In addition, when I use BSgenome in R to see the sequences around the pSu site, I found that the provided position is neither A or T site. I use the hg38 reference file downloaded from UCSC when running your package, and below is the R code:

  path <- '/data/yuxin/2021Fall/HomoSapiens/HEK293/HEK_WT/nanopsu_result/alignment/prediction.csv'
  table <- as.data.frame(read.csv(path))
  g <- table[table$prob_modified>0.5,]
  g$chr <- unlist(strsplit(g$transcript_ID,'_'))[seq(1,nrow(g)*2,2)]
  g$strand <- unlist(strsplit(g$transcript_ID,'_'))[seq(2,nrow(g)*2+1,2)]
  R <- g[g$strand=='R',]
  R_gr <- GRanges(seqnames = R$chr,
                  IRanges(start = R$position,width = 1),strand = "+")
  summary(as.factor(as.character(DNAStringSet(Views(BSgenome.Hsapiens.UCSC.hg38,R_gr)))))

output: 
    A     C     G     N     T 
33335 23691 23946  9964 33486 

command to run the package (I made some adjustment to your code so that I can store files in my preference):

nanopsu alignment -i /data/yuxin/2021Fall/HomoSapiens/HEK293/HEK_WT/fastq_guppy \
-r /data/yuxin/2021Fall/Reference/HomoSapiens/hg38_bychr.fa \
-o /data/yuxin/2021Fall/HomoSapiens/HEK293/HEK_WT/nanopsu_result

nanopsu remove_intron -o /data/yuxin/2021Fall/HomoSapiens/HEK293/HEK_WT/nanopsu_result
nanopsu extract_features -o /data/yuxin/2021Fall/HomoSapiens/HEK293/HEK_WT/nanopsu_result

nanopsu prediction -o /data/yuxin/2021Fall/HomoSapiens/HEK293/HEK_WT/nanopsu_result

Can you give some clues?

**Comment by sihaohuanguc** [comment]
Hello. Thank you for using our package. The "R" means minus strand, which is the reverse complementary strand of your provided strand. And the position index in the result is based on its own strand. For the "R" strand, the index starts at the 5' end of the "R" strand. I think you didn't see A or T as BSgenome view those positions as indexes on the forward strand.

**Comment by yuxinPenny** [comment]
Thank you for your explanation. I changed the strand information according to your explanation, but it does not work.

**Comment by sihaohuanguc** [comment]
Hello, I ran a sample with human hg38 and found that the 3 positions you mentioned on chr1_R are actually all "A" sites but not "T" sites in the generated reference for chr1 reverse strand. I think you introduced some bugs when you try to modify the codes. Maybe you could try to run one sample with my original version of codes and check whether the results changes (those three positions are not supposed to appear in the results as they are not T).
